config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  
  resources :users

  resources :products do
    resources :comments
  end

  resources :payments
  post "/payments/create"
  

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  post 'static_pages/thank_you'

  root 'static_pages#landing_page'

  resources :orders, only: [:index, :show, :new, :create]  
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :orders
  has_many :comments

  def average_rating
  comments.average(:rating).to_f
  end

  validates :name, presence: true

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      @products = Product.where("name LIKE ?", "%#{search_term}%")
    else
      @products = Product.all
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    @comments = Comment.paginate(page: params[:page], :per_page => 3) 
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_path, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: products_path }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s,:number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_comments.html.erb
<div class="comments">
  <% @comments.each do |comment| %>
  <div class="row comments_row">
      <hr>
      <p>
        <%= comment.user.first_name %>  <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
          <% if signed_in? && current_user.admin? %>
          <%= link_to ('<span class="glyphicon glyphicon-remove" id="destroycomment"></span>').html_safe, product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </p>
      <p><%= "Rating: #{comment.rating}/5" %></p>
      <div class="rated" data-score="<%= comment.rating %>"></div>
      <p><%= comment.body %></p>
  </div>
  <% end %>
  <!--<%= will_paginate @comments %>-->
  <div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @comments %>
    </div>
    <%= will_paginate @comments, :container => false %>
  </div>
</div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :colour %><br>
    <%= f.text_field :colour %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price, :step => 0.01 %>€
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_new_comment.html.erb
<div id="new-comment-id">
  <% if signed_in? %>
      <h4>Leave a review:</h4>
      <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
        <p>
          <%= f.label :body, "Comments" %><br>
          <%= f.text_area :body %>
        </p>
        <p>
          <div class="rating"></div>
        </p>  
        <p>
          <%= f.submit "Submit" %>
        </p>
      <% end %>
  <% end %>   
</div>

app/views/products/_product.html.erb
<tr>
  <td><%= product.name %></td>
  <td><%= product.description %></td>
  <td><%= product.image_url %></td>
  <td><%= product.colour %></td>
  <td><%= product.price %></td>
  <td><%= link_to 'Show', product %></td>
  <td><%= link_to 'Edit', edit_product_path(product) %></td>
  <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/products/edit.html.erb
<div class="product-edit">
  <h1>Editing product</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @product %> |
  <%= link_to 'Back', products_path %>
</div>

app/views/products/index.html.erb
<div class="product-index">
  <%# cache(cache_key_for_products) do %>
  <h1>List of Products</h1>

  <div class="table-responsive">
    <table class="product-table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Image</th>
          <th>Colour</th>
          <th>Price</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <%# cache(p) do %>
          <%= render @products %>
        <%# end %>
      </tbody>
    </table>
  </div>

  <br>

  <%= link_to 'New Product', new_product_path %>
  <%# end %>
</div>

app/views/products/new.html.erb
<div class="product-new">
  <h1>New product</h1>

  <%= render 'form' %>

  <%= link_to 'Back', products_path %>
</div>

app/views/products/show.html.erb
<div class="product-show">
  <p id="notice"><%= notice %></p>

  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-6">
        <p class="product-image">
          <%= image_tag @product.image_url, :data => { :action => "zoom"} %>
        </p>
      </div>
      <div class="col-xs-12 col-md-6">
        <p>
          <strong>Name:</strong>
          <br>
          <%= @product.name %>
        </p>

        <p>
          <strong>Description:</strong>
          <br>
          <%= @product.description %>
        </p>

        <p>
          <strong>Colour:</strong>
          <br>
          <%= @product.colour %>
        </p>

        <p>
          <strong>Price:</strong>
          <br>
          <%= @product.price %>€
        </p>

        <p>
          <strong>Average Rating:</strong> 
          <div class="rated" data-score="<%= @product.average_rating %>"></div> 
        </p>
      </div>
    </div> <!-- /row -->
  </div> <!-- /container -->
  

  <%= form_tag "/payments/create" do %>
    <%= render partial: "shared/stripe_checkout_button" %>
  <% end %>

  <%= render 'new_comment' %>
  <div id="newcomment"></div>
  <%= render 'comments' %>

  <%= link_to 'Edit', edit_product_path(@product) %> |
  <%= link_to 'Back', products_path %>
</div>