config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  
  resources :users

  resources :products do
    resources :comments
  end

  resources :payments
  post "/payments/create"
  

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  post 'static_pages/thank_you'

  root 'static_pages#landing_page'

  resources :orders, only: [:index, :show, :new, :create]  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>THE STORE</title>

    <!-- Google Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Exo:300,400,500' rel='stylesheet' type='text/css'>

    <!-- CSS-Styles -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
    <link href="css/zoom.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <!-- JavaScript -->
    <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>  
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <script src="js/zoom.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= csrf_meta_tags %>
  </head>
  <body>

<!-- ===== Navbar ===== -->
    <!--<nav class="header">-->
    <nav class="navbar navbar-static-top navbar-default" role="navigation">
      <!--<div class="navigation">-->
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse">
          <!--<ul class="navlist">-->
          <ul class="nav navbar-nav">
            <li id="first-site"><%= link_to "Home", static_pages_index_path %></li>
            <li><%= link_to "About", static_pages_about_path %></li>
            <li><%= link_to "Contact", static_pages_contact_path %></li>
            <li><%= link_to "Products", products_path %></li>
            <li><%= link_to "Users", users_path %></li>
            <% if user_signed_in? %>
              <li>
              <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
              </li>
            <% else %>
              <li>
              <%= link_to('Login', new_user_session_path)  %>  
              </li>
            <% end %>
          </ul>
          <div>
            <%= form_tag("/products", :method => "get", :class => "searchbox") do %>
              <%= label_tag(:q, "", :id => "searchtext") %>
              <%= text_field_tag(:q, nil, :id => "searchfield") %>
              <%= submit_tag("Search", :id => "searchbutton") %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="headlines">
        <h1>THE STORE</h1>
        <h2>Experience the place where everything is possible...</h2>
      </div>
    </nav>

<!-- ===== Yield ===== -->
    <div class="page-content">
      <p class="notice"><%= notice %></p>
      <%= yield %>  
    </div>

<!-- ===== Footer ===== -->
    <footer class="app_footer">
      <div class="footer-content">
        <div class="copyright">
          <p>&copy; THE STORE Ltd. 2015 </p>
        </div>
        <div class="previous-page">
          <%= link_to "Back", :back %>    
         </div>
      </div>
    </footer>

  </body>
</html>